version: '3'
services:
  monitor-space-hazards:
    build:
      context: .
      args:
        - ENV_COSMIC_BUCKET_SLUG=${COSMIC_BUCKET_SLUG}
        - ENV_COSMIC_READ_KEY=${COSMIC_READ_KEY}
        - ENV_NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN={NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
    ports:
      - '3000:3000'
    env_file: .env
