version: '3'
services:
  monitor-space-hazards:
    build:
      context: .
      args:
        - ENV_COSMIC_BUCKET_SLUG=${COSMIC_BUCKET_SLUG}
        - ENV_COSMIC_READ_KEY=${COSMIC_READ_KEY}
        - ENV_NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
        - ENV_NEXT_PUBLIC_PUBLIC_GA=${NEXT_PUBLIC_PUBLIC_GA}
        - SKIP_ENV_VALIDATION=1
    ports:
      - '3000:3000'
    env_file: .env
