export enum REVALIDATION_TAGS {
  GET_USERS_ME = 'get-users-me',
  GET_ORGANISATIONS = 'get-organisations',
  GET_BANNERS = 'get-banners',
  GET_ANALYSES = 'get-analyses',
  GET_MANOEUVRE = 'get-manoeuvre',
  GET_EPHEMERISES = 'get-ephemerises',
  GET_CONJUNCTION_UNIQUE_EVENT = 'get-conjunction-unique-event',
  GET_CONJUNCTION_ALERT_LATEST = 'get-conjunction-alert-latest',
  GET_ALERTS = 'get-alerts',
  GET_USERS = 'get-users',
  GET_REENTRY_EVENT = 'get-reentry-event',
  GET_REENTRY_ALERT_LATEST = 'get-reentry-alert-latest',
  GET_FRAGMENTATION_EVENT = 'get-fragmentation-event',
  GET_FRAGMENTATION_ALERT_LATEST = 'get-fragmentation-alert-latest',
}
