export enum QUERY_KEYS {
  Conjunctions = 'conjunctions',
  Satellites = 'satellites',
  Organisations = 'organisations',
  Analyses = 'analyses',
  Ephemerises = 'ephemerises',
  Activities = 'activities',
  Manoeuvres = 'manoeuvres',
  Reentries = 'reentries',
  Fragmentations = 'fragmentations',
  DataPerformance = 'data-performance',
  NotificationsSent = 'notifications-sent',
  StatsAnalysisAndManoeuvreSupport = 'stats-analysis-and-manoeuvre-support',
  StatsConjunctionEventByType = 'stats-conjunction-event-by-type',
  StatsReentryEventByType = 'stats-reentry-event-by-type',
  StatsFragmentationEventByType = 'stats-fragmentation-event-by-type',
  StatsEventByOrganisation = 'stats-event-by-organisation',
  StatsEventBySatellite = 'stats-event-by-satellite',
  StatsConjunctionEventByProbabilityOfCollision = 'stats-conjunction-event-by-probability-of-collision',
  StatsNotificationsSent = 'stats-notifications-sent',
  DataPerformanceAggregated = 'data-performance-aggregated',
}
