name: Build and Deploy to AWS DEV

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: frontend2

jobs:
  build_and_push_awsdev:
    runs-on: ubuntu-latest
    # needs: execute_e2e_fe_tests #todo
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/frontend_ecr_role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Create and use a new builder instance
        run: |
          docker buildx create --name mybuilder --use

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            ENV_COSMIC_BUCKET_SLUG=${{ secrets.COSMIC_BUCKET_SLUG }}
            ENV_COSMIC_READ_KEY=${{ secrets.COSMIC_READ_KEY }}
            ENV_NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          builder: mybuilder
          cache-from: type=registry,ref=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:cache
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:cache

#  deploy_awsdev:
#    name: Invoke deploy to AWS DEV workflow
#    needs: build_and_push_awsdev
#    runs-on: ubuntu-latest
#    steps:
#      - name: Invoke deploy workflow with inputs
#        uses: benc-uk/workflow-dispatch@v1
#        with:
#          workflow: deploy-to-aws.yml
#          repo: UKSpaceAgency/sst-beta-infra
#          ref: main
#          token: ${{ secrets.INFRA_REPO_TOKEN }}
#          inputs: '{ "invoker": "frontend2", "env": "dev", "image-tag":"${{ github.sha }}"}'
